#spring:
#  rabbitmq:
#    host: bulldog.rmq.cloudamqp.com
#    port: 1883
#    username: cksfjsfl
#    password: w3DKiQBs1kr4XRGiu3NrjpUTFr1ASIhi
#    virtual-host: cksfjsfl
#    vhost: cksfjsfl
#    #    host: 127.0.0.1
#    #    port: 5672
#    #    username: guest
#    #    password: guest
#
#    maxConnections: 10
#    maxConcurrentConsumers: 5
#    indentJson: true
##destinations:
##  queues:
##    NYSE:
##      exchange: nyse
##      routing-key: NYSE
##    IBOV:
##      exchange: ibov
##      routing-key: IBOV
##  topics:
##    weather:
##      exchange: alerts
##      routing-key: WEATHER
##
##
##
##
##
##
