drop table test_entity if exists
drop table user if exists
drop sequence if exists hibernate_sequence
create table test_entity (id bigint not null, version integer, test_long bigint, test_some_string_date varchar(255), test_string varchar(255), primary key (id))
create table user (id bigint generated by default as identity, created_date timestamp, last_login_date binary(255), modified_date timestamp, name varchar(255), password varchar(255), version bigint, modified_by_id bigint, primary key (id))
alter table user add constraint UK_gj2fy3dcix7ph7k8684gka40c  unique (name)
alter table user add constraint FK_tca13gr0ca5uqivusrcgywy1p foreign key (modified_by_id) references user